### ISSUE TITLE
feature request: make "it's" optional

### ISSUE THREAD

**Issue by chriscamacho** [pknoe3lh/WordClockGenerator#5]
as title, personally i'd rather see "ten past four" than "its ten past four"

**Comment by im-pro-at** [comment]
If all is entered and the table in the right looks good you can make additional adjustments there. But be careful if you change anything else they will be overridden. I used that to display "I love You" at a random time once a day. It took my girlfriend 3 Month to see that.

**Comment by chriscamacho** [comment]
nice ! long three months waiting for your brownie points though!

to be honest I ended up hacking line 129 of JPTimeToWords.java....

**Comment by im-pro-at** [comment]
Oh this text box is also in the GUI. There you can type what you want. And the keywords will be replaced.

**Comment by pknoe3lh** [comment]
Oh this text box is also in the GUI. There you can type what you want. And the keywords will be replaced.
